acme_project/acme_project/urls.py
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.urls import include, path, reverse_lazy
from django.views.generic.edit import CreateView
from django.conf.urls.static import static
from django.conf import settings
from users.forms import CustomUserCreationForm

handler404 = 'core.views.page_not_found'


urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('birthday/', include('birthday.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
         'auth/registration/',
         CreateView.as_view(
                            template_name='registration/registration_form.html',
                            form_class=CustomUserCreationForm,
                            success_url=reverse_lazy('pages:homepage'),
         ),
         name='registration',
        ),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acme_project/birthday/urls.py
from django.urls import path

from . import views

app_name = 'birthday'

urlpatterns = [
    path('', views.BirthdayCreateView.as_view(), name='create'),
    path('<int:pk>/', views.BirthdayDetailView.as_view(), name='detail'),
    path('list/', views.BirthdayListView.as_view(), name='list'),
    path('<int:pk>/edit/', views.BirthdayUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', views.BirthdayDeleteView.as_view(), name='delete'),
    path('login_only/', views.simple_view),
    # path('<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('<int:pk>/comment/', views.CongratulationCreateView.as_view(), name='add_comment'),
]

acme_project/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
]

acme_project/birthday/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from .validators import real_age

User = get_user_model()


class Tag(models.Model):
    tag = models.CharField('Тег', max_length=20)

    def __str__(self):
        return self.tag


class Birthday(models.Model):
    first_name = models.CharField('Имя', max_length=40)
    last_name = models.CharField(
        'Фамилия', blank=True, help_text='Необязательное поле',
        max_length=20
    )
    birthday = models.DateField('Дата рождения',
                                validators=(real_age,)
                                )
    image = models.ImageField('Фото',
                              upload_to='birthdays_images',
                              blank=True)
    author = models.ForeignKey(User, verbose_name='Автор записи',
                               on_delete=models.CASCADE,
                               null=True
                               )
    tags = models.ManyToManyField(
        Tag,
        verbose_name='Теги',
        blank=True,
        help_text='Удерживайте Ctrl для выбора нескольких вариантов'
    )

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=('first_name', 'last_name', 'birthday'),
                name='Unique person constraint',
            ),
        )

    def get_absolute_url(self):
        # С помощью функции reverse() возвращаем URL объекта.
        return reverse('birthday:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Congratulation(models.Model):
    text = models.TextField('Текст поздравления')
    birthday = models.ForeignKey(
        Birthday,
        on_delete=models.CASCADE,
        related_name='congratulations',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created_at',)

acme_project/birthday/forms.py
from django import forms
from .models import Birthday, Congratulation
from django.core.exceptions import ValidationError


BEATLES = {'Джон Леннон', 'Пол Маккартни', 'Джордж Харрисон', 'Ринго Старр'}


class BirthdayForm(forms.ModelForm):
    class Meta:
        model = Birthday
        exclude = ('author',)
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        return first_name.split()[0]

    def clean(self):
        super().clean()
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        if f'{first_name} {last_name}' in BEATLES:
            # Отправляем письмо, если кто-то представляется
            # именем одного из участников Beatles.
            send_mail(
                subject='Another Beatles member',
                message=f'{first_name} {last_name} пытался опубликовать запись!',
                from_email='birthday_form@acme.not',
                recipient_list=['admin@acme.not'],
                fail_silently=True,
            )
            raise ValidationError(
                'Мы тоже любим Битлз, но введите, пожалуйста, настоящее имя!'
            )


class CongratulationForm(forms.ModelForm):
    class Meta:
        model = Congratulation
        fields = ('text',)

acme_project/birthday/views.py
from django.shortcuts import get_object_or_404, redirect
# from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, UpdateView)
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
# from django.contrib.auth import get_user_model

from .forms import BirthdayForm, CongratulationForm
from .models import Birthday, Congratulation
from .utils import calculate_birthday_countdown


from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView

from .forms import CongratulationForm
from .models import Birthday, Congratulation


# User = get_user_model()


@login_required
def simple_view(request):
    return HttpResponse('Страница для залогиненных пользователей!')


class BirthdayCreateView(LoginRequiredMixin, CreateView):
    model = Birthday
    form_class = BirthdayForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class BirthdayUpdateView(LoginRequiredMixin, UpdateView):
    model = Birthday
    form_class = BirthdayForm

    def dispatch(self, request, *args, **kwargs):
        # При получении объекта не указываем автора.
        # Результат сохраняем в переменную.
        instance = get_object_or_404(Birthday, pk=kwargs['pk'])
        # Сверяем автора объекта и пользователя из запроса.
        if instance.author != request.user:
            # Здесь может быть как вызов ошибки, так и редирект на нужную страницу.
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

# def birthday(request, pk=None):
#     if pk is not None:
#         # Получаем объект модели или выбрасываем 404 ошибку.
#         instance = get_object_or_404(Birthday, pk=pk)
#     else:
#         # Связывать форму с объектом не нужно, установим значение None.
#         instance = None
#     form = BirthdayForm(request.POST or None,
#                         files=request.FILES or None,
#                         instance=instance)
#     # Создаём словарь контекста сразу после инициализации формы.
#     context = {'form': form}
#     # Если форма валидна...
#     if form.is_valid():
#         form.save()
#         # ...вызовем функцию подсчёта дней:
#         birthday_countdown = calculate_birthday_countdown(
#             # ...и передаём в неё дату из словаря cleaned_data.
#             form.cleaned_data['birthday']
#         )
#         # Обновляем словарь контекста: добавляем в него новый элемент.
#         context.update({'birthday_countdown': birthday_countdown})
#     return render(request, 'birthday/birthday_form.html', context)


class BirthdayListView(ListView):
    model = Birthday
    queryset = (Birthday.objects
                .prefetch_related('tags')
                .select_related('author'))
    ordering = 'id'
    paginate_by = 10

# def birthday_list(request):
#     # Получаем все объекты модели Birthday из БД.
#     birthdays = Birthday.objects.order_by('id')
#     paginator = Paginator(birthdays, 10)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     # Передаём их в контекст шаблона.
#     context = {'page_obj': page_obj}
#     return render(request, 'birthday/birthday_list.html',
#                   context)


# def delete_birthday(request, pk):
#     instance = get_object_or_404(Birthday, pk=pk)
#     form = BirthdayForm(instance=instance)
#     context = {'form': form}
#     if request.method == 'POST':
#         instance.delete()
#         return redirect('birthday:list')
#     return render(request, 'birthday/birthday_form.html', context)

class BirthdayDeleteView(LoginRequiredMixin, DeleteView):
    model = Birthday
    success_url = reverse_lazy('birthday:list')

    def dispatch(self, request, *args, **kwargs):
        # Получаем объект по первичному ключу и автору или вызываем 404 ошибку.
        instance = get_object_or_404(Birthday, pk=kwargs['pk'])
        # Сверяем автора объекта и пользователя из запроса.
        if instance.author != request.user:
            # Здесь может быть как вызов ошибки, так и редирект на нужную страницу.
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class BirthdayDetailView(DetailView):
    model = Birthday

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['birthday_countdown'] = calculate_birthday_countdown(
            self.object.birthday
        )
        context['form'] = CongratulationForm()
        context['congratulations'] = (
            # Дополнительно подгружаем авторов комментариев,
            # чтобы избежать множества запросов к БД.
            self.object.congratulations.select_related('author'))
        return context


# @login_required
# def add_comment(request, pk):
#     # Получаем объект дня рождения или выбрасываем 404 ошибку.
#     birthday = get_object_or_404(Birthday, pk=pk)
#     # Функция должна обрабатывать только POST-запросы.
#     form = CongratulationForm(request.POST)
#     if form.is_valid():
#         # Создаём объект поздравления, но не сохраняем его в БД.
#         congratulation = form.save(commit=False)
#         # В поле author передаём объект автора поздравления.
#         congratulation.author = request.user
#         # В поле birthday передаём объект дня рождения.
#         congratulation.birthday = birthday
#         # Сохраняем объект в БД.
#         congratulation.save()
#     # Перенаправляем пользователя назад, на страницу дня рождения.
#     return redirect('birthday:detail', pk=pk)

class CongratulationCreateView(LoginRequiredMixin, CreateView):
    birthday = None
    model = Congratulation
    form_class = CongratulationForm

    # Переопределяем dispatch()
    def dispatch(self, request, *args, **kwargs):
        self.birthday = get_object_or_404(Birthday, pk=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    # Переопределяем form_valid()
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.birthday = self.birthday
        return super().form_valid(form)

    # Переопределяем get_success_url()
    def get_success_url(self):
        return reverse('birthday:detail', kwargs={'pk': self.birthday.pk})

acme_project/templates/birthday/birthday.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

acme_project/templates/birthday/birthday_confirm_delete.html
<!-- birthday/birthday_confirm_delete.html -->
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
  <!-- Обращаемся через object -->
  <h1>Удалить запись {{ object.pk }}</h1>
  <div class="card col-4 m-3">
    <div class="card-header">
      <!-- Обращаемся через birthday -->
      {{ birthday.first_name }} {{ birthday.last_name }} - {{ birthday.birthday }}
    </div>
    <div class="card-body">
      <!-- В форме только csrf-токен и кнопка. Никакие другие поля тут не нужны.  -->
      <form method="post">
        {% csrf_token %}
        {% bootstrap_button button_type="submit" content="Удалить" %}
      </form>
    </div>
  </div>
{% endblock content %}

acme_project/templates/birthday/birthday_detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  ID записи: {{ object.id }} <br>
  Автор: {{ object.author.first_name }} {{ object.author.last_name }}
  <div>
  {% with all_tags=birthday.tags.all %}
          <!-- Если у записи есть хоть один тег -->
    {% if all_tags %}
            <!-- Выводим теги через запятую, самую первую букву делаем заглавной -->
      {{ all_tags|join:", "|lower|capfirst }} автора

    {% endif %}
  {% endwith %}
  </div>
  <hr>
  {% if birthday.image %}
    <div>
      <img src="{{ birthday.image.url }}" height="200">
    </div>
  {% endif %}
   <h2>Привет, {{ object.first_name }} {{ object.last_name }}</h2>
  {% if birthday_countdown == 0 %}
    <p>С днём рождения!</p>
  {% else %}
    <p>Осталось дней до дня рождения: {{ birthday_countdown }}!</p>
  {% endif %}

  <div>
    <h3>Поздравления:</h3>
    <!-- Если пользователь залогинен, отображаем форму -->
    {% if user.is_authenticated %}
      <!-- Указываем, на какой адрес нужно отправить POST-запрос -->
      <form action="{% url 'birthday:add_comment' object.pk %}" method="post" class="col-3">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Отправить поздравление" %}
      </form>
    {% endif %}
    <!-- В цикле перебираем и выводим поздравления -->
    {% for congratulation in congratulations %}
      <hr>
      <p>
        {{ congratulation.author.username }}
        поздравил {{ congratulation.created_at|date:"d M Y H:i" }}
      </p>
      <p><b>{{ congratulation.text }}</b></p>
    {% endfor %}
  </div>
{% endblock content %}

acme_project/templates/birthday/birthday_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
{#  {% with data=form.instance %}#}
  {% if '/edit/' in request.path %}
    <h2>Редактировать запись {{ data.pk }}</h2>
{#    {% elif "/delete/" in request.path %}#}
{#      <h1>Удалить запись {{ data.pk }}</h1>#}
  {% else %}
    <h2>Создать запись</h2>
  {% endif %}
  <div class="card col-4">
{#      <div class="card-header">#}
{#        Калькулятор ожидания дня рождения#}
{#      </div>#}
      <div class="card-header">
        Калькулятор ожидания дня рождения
      </div>
{#       <form method="post" enctype="multipart/form-data">#}
{#         {% csrf_token %}#}
{#          {% if not "/delete/" in request.path %}#}
{#          {% bootstrap_form form %}#}
{#          {% else %}#}
{#          <p>{{ form.instance.first_name }} {{ form.instance.last_name }}</p>#}
{#          <p>{{ form.instance.birthday }}</p>#}
{#        {% endif %}#}
{#         {% bootstrap_button button_type="submit" content="Oтправить" %}#}
{#      </form>#}
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Отправить" %}
      </form>
    </div>
  </div>

{#  {% if form.is_valid %}#}
{#    ID записи в БД: {{ data.id }}#}
{#    <h2>Привет, {{ data.first_name }} {{ data.last_name }}</h2>#}
{##}
{#    {% if birthday_countdown == 0 %}#}
{##}
{#      С днём рождения!#}
{##}
{#    {% else %}#}
{##}
{#      Осталось дней до дня рождения: {{ birthday_countdown }}!#}
{#    {% endif %}#}
{#  {% endif %}#}
{#{% endwith %}#}

{% endblock %}

acme_project/templates/birthday/birthday_list.html
<!-- templates/birthday/birthday_list.html -->
{% extends "base.html" %}

{% block content %}
  {% for birthday in page_obj %}
    <!-- Добавим класс row: каждая запись — это строка -->
    <div class="row">
      <!-- Первая "колонка" в строке, её ширина — 2/12 -->
      <div class="col-2">
        {% if birthday.image %}
          <!-- У объекта картинки image есть атрибут url — его и укажем в src -->
          <img src="{{ birthday.image.url }}" height="80">
        {% endif %}
      </div>

      <!-- Вторая "колонка" в строке, её ширина — 10/12 -->
      <div class="col-10">
  <div>
    {{ birthday.first_name }} {{ birthday.last_name }} - {{ birthday.birthday }}<br>
    <a href="{% url 'birthday:detail' birthday.id %}">Сколько до дня рождения?</a>
  </div>
       <div>
          <!-- Тег spaceless убирает из строки лишние пробелы
            и переводы строк -->
{#          {% spaceless %}#}
{#            <!-- Цикл по тегам записи -->#}
{#            {% for tag in birthday.tags.all %}#}
{#              <!-- Если работаем с первым элементом цикла... -->#}
{#              {% if forloop.first %}#}
{#                <!-- ...выводим название тега с заглавной буквы -->#}
{#                <span>{{ tag.tag|title }}</span>#}
{#              {% else %}#}
{#                <!-- Если элемент не первый — пишем тег с маленькой буквы -->#}
{#                <span>{{ tag.tag|lower }}</span>#}
{#              {% endif %}#}
{#              <!-- Если обрабатываем не последний элемент цикла... -->#}
{#              {% if not forloop.last %}#}
{#                <!-- ...после него ставим запятую с пробелом -->#}
{#                <span>, </span>#}
{#              {% else %}#}
{#                <!-- После последнего элемента выводим username пользователя -->#}
{#                пользователя {{ birthday.author.username }}#}
{#              {% endif %}#}
{#            {% endfor %}#}
{#          {% endspaceless %}#}

        <!-- Чтобы сократить количество кода —
          введём переменную all_tags, в которой будут лежать все теги объекта -->
        {% with all_tags=birthday.tags.all %}
          <!-- Если у записи есть хоть один тег -->
          {% if all_tags %}
            <!-- Выводим теги через запятую, самую первую букву делаем заглавной -->
            {{ all_tags|join:", "|lower|capfirst }}
            <!-- Также выводим username пользователя -->
            пользователя {{ birthday.author.username }}
          {% endif %}
        {% endwith %}
      </div>

        {% if birthday.author == user %}
        <div>
          <a href="{% url 'birthday:edit' birthday.id %}">Изменить запись</a> | <a href="{% url 'birthday:delete' birthday.id %}">Удалить запись</a>
        </div>
        {% endif %}
      </div>
      {% if not forloop.last %}
        <hr class="mt-3">
      {% endif %}
    </div>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}